name: Run PowerShell Script

on:
  workflow_dispatch:
    inputs: 
        name: #Taking input
            required: true
    
    

jobs:
  run-powershell:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run PowerShell Script
        shell: pwsh
        run:  ./myscript.ps1
  # Specify the path to your .ps1 file
