name: Run PowerShell Script

on:
  push:
    branches:
      - main

jobs:
  run-powershell:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run PowerShell Script
        shell: pwsh
        run:  ./myscript.ps1
  # Specify the path to your .ps1 file
